import { useMemo, useState, type ReactNode } from 'react';
import { Link } from '@tanstack/react-router';
import {
  Alert,
  Badge,
  Card,
  Group,
  Paper,
  SegmentedControl,
  Stack,
  Table,
  Text,
} from '@mantine/core';
import { IconAlertTriangle, IconFlask, IconMap } from '@tabler/icons-react';
import { useContentList } from '@/api/hooks';
import { ErrorState, LoadingState } from '@/components/QueryState';
import { PageHeader } from '@/components/PageHeader';
import {
  DIFFICULTY_ORDER,
  chaptersOf,
  gapsIn,
  gridFor,
  stageRows,
  type ContentRow,
  type StageRow,
} from './stageGrid';

/**
 * The campaign editor (ADMIN_SUITE_DESIGN §2.6).
 *
 * **A reviewing view rather than an authoring one**, and that follows from how the content
 * got here: the game repo's seed generates 252 campaign stages from twelve chapter plans,
 * so nobody is ever going to create one of these by hand. What an operator does is look at
 * what the seed produced and retune it — and the question they arrive with is almost always
 * comparative. "Is 4-6 Brutal out of line with 4-5" is one glance across a row here, and a
 * search through a flat list of 252 anywhere else.
 *
 * Every cell links to the generic entity editor rather than reimplementing one. A second
 * place to change a stage's fields is a second place for them to drift, and the browser's
 * editor is already schema-driven, validated and wired to the publish flow. What this adds
 * is the *shape* — which is the only thing the browser cannot give.
 */
export function CampaignPage(): ReactNode {
  const stages = useContentList('stages');
  const chaptersList = useContentList('chapters');
  const [chapter, setChapter] = useState<string | null>(null);

  const rows = useMemo(() => stageRows((stages.data?.items ?? []) as ContentRow[]), [stages.data]);
  const chapters = useMemo(() => chaptersOf(rows), [rows]);
  const current = chapter ?? chapters[0] ?? null;
  const grid = useMemo(() => (current ? gridFor(rows, current) : []), [rows, current]);
  const gaps = useMemo(() => gapsIn(grid), [grid]);

  const chapterName = (key: string): string => {
    const entry = (chaptersList.data?.items ?? []).find((item) => item.key === key);
    const data = entry?.data as { name?: unknown } | undefined;
    return typeof data?.name === 'string' ? data.name : key;
  };

  if (stages.isPending) return <LoadingState label="Loading the campaign" />;
  if (stages.error)
    return <ErrorState error={stages.error} onRetry={() => void stages.refetch()} />;

  return (
    <>
      <PageHeader
        title="Campaign"
        description="Twelve chapters, seven stages, three difficulties — laid out the way they are compared."
      />

      {rows.length === 0 ? (
        <Paper withBorder p="xl">
          <Stack align="center" gap="xs">
            <IconMap size={32} opacity={0.4} />
            <Text c="dimmed" size="sm" ta="center">
              No campaign stages are published. They are generated by the game repo&rsquo;s seed —
              run it, or publish the drafts.
            </Text>
          </Stack>
        </Paper>
      ) : (
        <Stack gap="md">
          <Paper withBorder p="md">
            <Text size="sm" fw={500} mb={6}>
              Chapter
            </Text>
            <SegmentedControl
              value={current ?? ''}
              onChange={setChapter}
              data={chapters.map((key) => ({ value: key, label: key.replace(/^c0?/, '') }))}
              fullWidth
            />
            {current && (
              <Text size="xs" c="dimmed" mt={6}>
                {chapterName(current)}
              </Text>
            )}
          </Paper>

          {gaps.length > 0 && (
            <Alert
              icon={<IconAlertTriangle size={16} />}
              color="orange"
              variant="light"
              title="This chapter has holes"
            >
              {/* Kept visible rather than closed up: a chapter with six Brutal stages and
                  seven of everything else is a fault, and the grid exists to show it. */}
              No stage at {gaps.join(', ')}. A difficulty a player can reach and not play is a dead
              end rather than a short chapter.
            </Alert>
          )}

          <Card>
            <Table highlightOnHover>
              <Table.Thead>
                <Table.Tr>
                  <Table.Th w={70}>Stage</Table.Th>
                  {DIFFICULTY_ORDER.map((difficulty) => (
                    <Table.Th key={difficulty} tt="capitalize">
                      {difficulty}
                    </Table.Th>
                  ))}
                </Table.Tr>
              </Table.Thead>
              <Table.Tbody>
                {grid.map((cell) => (
                  <Table.Tr key={cell.number}>
                    <Table.Td>
                      <Text fw={600} size="sm">
                        {current?.replace(/^c0?/, '')}-{cell.number}
                      </Text>
                    </Table.Td>
                    {DIFFICULTY_ORDER.map((difficulty) => (
                      <Table.Td key={difficulty}>
                        <Cell stage={cell.byDifficulty[difficulty] ?? null} />
                      </Table.Td>
                    ))}
                  </Table.Tr>
                ))}
              </Table.Tbody>
            </Table>
          </Card>

          <Text size="xs" c="dimmed">
            A cell opens the stage in the content editor, where every field is schema-driven and
            wired to the publish flow. To find out what a retune actually does before it ships, take
            the stage key to the{' '}
            <Link to="/balance">
              <Group component="span" gap={4} display="inline-flex">
                <IconFlask size={12} />
                balance sandbox
              </Group>
            </Link>
            .
          </Text>
        </Stack>
      )}
    </>
  );
}

/**
 * One stage in the grid.
 *
 * Energy, waves and unit count — the three figures a retune is compared on, and all three
 * already in the list response. Anything more would be a second stage editor.
 */
function Cell({ stage }: { stage: StageRow | null }): ReactNode {
  if (!stage) {
    return (
      <Text size="xs" c="dimmed" fs="italic">
        missing
      </Text>
    );
  }
  return (
    <Link
      to="/content/$typePath/$key"
      params={{ typePath: 'stages', key: stage.key }}
      style={{ textDecoration: 'none' }}
    >
      <Group gap={6} wrap="nowrap">
        <Text size="xs" ff="monospace">
          {stage.energyCost}⚡
        </Text>
        <Text size="xs" c="dimmed">
          {stage.waves}w · {stage.units}u
        </Text>
        {stage.state !== 'live' && (
          <Badge size="xs" variant="light" color="orange">
            {stage.state}
          </Badge>
        )}
      </Group>
    </Link>
  );
}
