/**
 * Generated by `pnpm sync-api` from MistvaleMobile/docs/openapi/admin-api.json.
 *
 * Do not edit. Change the Zod contracts in the game repo's
 * `packages/shared/src/openapi.ts`, run `pnpm openapi` there, then `pnpm sync-api` here.
 */

export interface paths {
    "/admin/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in to the Admin Suite
         * @description Requires an account with the `admin` rank. A correct password on a non-admin account returns the same error as a wrong one, so rank is not discoverable.
         */
        post: operations["adminLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End the admin session */
        post: operations["adminLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in admin account */
        get: operations["adminMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live and draft counts for every content type */
        get: operations["listContentTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/content/{type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every entity of one content type */
        get: operations["listContentEntries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/content/{type}/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One entity, with its live version alongside the draft */
        get: operations["getContentEntry"];
        /**
         * Save an entity as a draft
         * @description Writes never touch live content. The body is validated against the content type's schema, so field-level errors come back immediately rather than at publish.
         */
        put: operations["saveContentEntry"];
        post?: never;
        /**
         * Mark an entity for deletion at the next publish
         * @description Live entities are tombstoned rather than removed, so the publish diff can show the removal and validation can catch anything still referencing them.
         */
        delete: operations["deleteContentEntry"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/content/{type}/{key}/revert-draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Drop one pending draft, restoring the live version in the editor */
        post: operations["discardContentDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/content/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Field-level differences between live content and the drafts */
        get: operations["diffContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/content/discard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Discard every pending draft */
        post: operations["discardAllDrafts"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/content/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish the drafts
         * @description Validates first and refuses on any error. On success the whole content snapshot is swapped atomically and a revision is recorded, which is what makes revert possible.
         */
        post: operations["publishContent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/content/revert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore a previous revision
         * @description Recorded as a new revision rather than by rewinding history, so the audit trail stays append-only.
         */
        post: operations["revertContent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/content/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Publish history */
        get: operations["listContentRevisions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/content/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate the pending drafts without changing anything */
        post: operations["validateContent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/stats/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard counters and recent audit entries */
        get: operations["adminOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch the live content bundle
         * @description Served from memory and cached by revision. Send `If-None-Match` with the ETag from a previous response to get a 304 when content has not moved.
         */
        get: operations["getContentBundle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AccountSummary: {
            accountName: string;
            forcePasswordChange: boolean;
            id: string;
            /** @enum {string} */
            rank: "player" | "gamemaster" | "admin";
        };
        AdminLoginResponse: {
            account: components["schemas"]["AccountSummary"];
        };
        AdminLogoutResponse: {
            loggedOut: boolean;
        };
        AdminMeResponse: {
            account: components["schemas"]["AccountSummary"];
        };
        AdminOverview: {
            accounts: {
                admins: number;
                banned: number;
                total: number;
            };
            content: {
                champions: number;
                enemies: number;
                publishedAt: string | null;
                rev: number;
                skills: number;
                stages: number;
            };
            players: {
                activeToday: number;
                bots: number;
                total: number;
            };
            recentAudit: components["schemas"]["AuditEntry"][];
        };
        ApiError: {
            /** @enum {string} */
            code: "AUTH_REQUIRED" | "FORBIDDEN" | "VALIDATION" | "INVALID_CREDENTIALS" | "ALREADY_EXISTS" | "NOT_FOUND" | "INSUFFICIENT_FUNDS" | "ENERGY_LOW" | "ROSTER_FULL" | "COOLDOWN" | "LOCKED_CONTENT" | "IDEMPOTENT_REPLAY" | "RATE_LIMITED" | "CONTENT_STALE" | "ACCOUNT_BANNED" | "PASSWORD_CHANGE_REQUIRED" | "INTERNAL";
            details?: unknown;
            message: string;
            requestId?: string;
        };
        AssetDef: {
            /** @default  */
            avatarPath: string;
            basePath: string;
            key: string;
            /** @enum {string} */
            kind: "unit" | "vfx" | "ui" | "audio";
            /** @default 0 */
            sortOrder: number;
            /**
             * @default repo
             * @enum {string}
             */
            source: "repo" | "upload";
            /** @default  */
            stillPath: string;
            tint?: string;
            /** @default {} */
            tracks: {
                [key: string]: {
                    /** @default 9 */
                    fps: number;
                    frames: number;
                    /** @default false */
                    loop: boolean;
                };
            };
        };
        AuditEntry: {
            action: string;
            actor: string;
            createdAt: string;
            entity: string;
            entityId: string | null;
        };
        CampaignChapterDef: {
            /** @default  */
            backgroundAsset: string;
            key: string;
            /** @default  */
            lore: string;
            name: string;
            number: number;
            /** @default  */
            region: string;
            setKey?: string;
            /** @default 0 */
            sortOrder: number;
            /** @default [] */
            starRewards: {
                rewards: {
                    [key: string]: number;
                };
                stars: number;
            }[];
        };
        ChampionDef: {
            assetKey: string;
            /** @default null */
            aura: {
                /**
                 * @default any
                 * @enum {string}
                 */
                area: "any" | "campaign" | "arena" | "depths";
                /**
                 * @default all
                 * @enum {string}
                 */
                scope: "all" | "element" | "faction";
                /** @enum {string} */
                stat: "hp" | "atk" | "def" | "spd" | "critRate" | "critDmg" | "res" | "acc";
                value: number;
            } | null;
            /** @default 1 */
            balanceVersion: number;
            baseStats: {
                /** @default 0 */
                acc: number;
                atk: number;
                /** @default 50 */
                critDmg: number;
                /** @default 15 */
                critRate: number;
                def: number;
                hp: number;
                /** @default 30 */
                res: number;
                spd: number;
            };
            /** @enum {string} */
            element: "ember" | "tide" | "verdant" | "mist";
            factionKey: string;
            /** @default false */
            isFood: boolean;
            key: string;
            /** @default  */
            lore: string;
            name: string;
            /** @enum {string} */
            rarity: "common" | "uncommon" | "rare" | "epic" | "legendary";
            /** @enum {string} */
            role: "attack" | "defense" | "hp" | "support";
            skills: string[];
            /** @default 0 */
            sortOrder: number;
            /** @default false */
            starter: boolean;
            /** @default true */
            summonable: boolean;
            /** @default  */
            title: string;
        };
        ContentBundle: {
            assets: components["schemas"]["AssetDef"][];
            campaignChapters: components["schemas"]["CampaignChapterDef"][];
            champions: components["schemas"]["ChampionDef"][];
            config: {
                [key: string]: number | string | boolean | {
                    [key: string]: unknown;
                } | unknown[];
            };
            enemies: components["schemas"]["EnemyDef"][];
            factions: components["schemas"]["FactionDef"][];
            gearSets: components["schemas"]["GearSetDef"][];
            gearSlots: components["schemas"]["GearSlotDef"][];
            gearStats: components["schemas"]["GearStatDef"][];
            items: components["schemas"]["ItemDef"][];
            publishedAt: string | null;
            rev: number;
            shops: components["schemas"]["ShopDef"][];
            skills: components["schemas"]["SkillDef"][];
            stages: components["schemas"]["StageDef"][];
            statuses: components["schemas"]["StatusDef"][];
            summonPools: components["schemas"]["SummonPoolDef"][];
        };
        ContentDiff: {
            entries: components["schemas"]["ContentDiffEntry"][];
            rev: number;
            totals: components["schemas"]["ContentTotals"];
        };
        ContentDiffEntry: {
            /** @enum {string} */
            change: "added" | "modified" | "removed";
            contentType: string;
            fields: {
                after: unknown;
                before: unknown;
                path: string;
            }[];
            key: string;
            /** @enum {string} */
            risk?: "rates" | "balance" | "economy";
        };
        ContentEntry: {
            data: {
                [key: string]: unknown;
            };
            key: string;
            /** @enum {string} */
            state: "live" | "draft" | "deleting";
            updatedAt: string | null;
            updatedBy: string | null;
        };
        ContentIssue: {
            contentType: string;
            key: string;
            message: string;
            path?: string;
            /** @enum {string} */
            severity: "error" | "warning";
        };
        ContentRevisionSummary: {
            note: string;
            publishedAt: string;
            publishedBy: string;
            rev: number;
            summary: components["schemas"]["ContentTotals"];
        };
        ContentTotals: {
            added: number;
            modified: number;
            removed: number;
        };
        ContentTypeCount: {
            /** @enum {string} */
            contentType: "faction" | "status" | "skill" | "asset" | "champion" | "enemy" | "gearSet" | "gearSlot" | "gearStat" | "item" | "campaignChapter" | "stage" | "summonPool" | "shop" | "gameConfig";
            drafts: number;
            label: string;
            live: number;
            path: string;
        };
        ContentValidationResult: {
            checked: number;
            errors: components["schemas"]["ContentIssue"][];
            ok: boolean;
            warnings: components["schemas"]["ContentIssue"][];
        };
        DeleteContentEntryResponse: {
            /** @enum {string} */
            contentType: "faction" | "status" | "skill" | "asset" | "champion" | "enemy" | "gearSet" | "gearSlot" | "gearStat" | "item" | "campaignChapter" | "stage" | "summonPool" | "shop" | "gameConfig";
            key: string;
            pendingDelete: boolean;
        };
        DiscardAllDraftsResponse: {
            discarded: number;
        };
        DiscardContentDraftResponse: {
            /** @enum {string} */
            contentType: "faction" | "status" | "skill" | "asset" | "champion" | "enemy" | "gearSet" | "gearSlot" | "gearStat" | "item" | "campaignChapter" | "stage" | "summonPool" | "shop" | "gameConfig";
            discarded: boolean;
            key: string;
        };
        EnemyDef: {
            /** @default 60 */
            anchorLevel: number;
            archetype: string;
            assetKey: string;
            baseStats: {
                /** @default 0 */
                acc: number;
                atk: number;
                /** @default 50 */
                critDmg: number;
                /** @default 15 */
                critRate: number;
                def: number;
                hp: number;
                /** @default 30 */
                res: number;
                spd: number;
            };
            /**
             * @default {
             *       "almightyImmunity": false,
             *       "tmReductionImmune": false
             *     }
             */
            bossMechanics: {
                addSummon?: {
                    cap: number;
                    perTurn: number;
                    unitKey: string;
                };
                /** @default false */
                almightyImmunity: boolean;
                enrage?: {
                    afterTurn: number;
                    dmgPctPerTurn: number;
                };
                hitShield?: {
                    hits: number;
                    punishTmPct: number;
                };
                thresholdRetaliation?: {
                    perHpPct: number;
                    /** @default true */
                    skipIfDot: boolean;
                };
                /** @default false */
                tmReductionImmune: boolean;
            };
            /** @enum {string} */
            element: "ember" | "tide" | "verdant" | "mist";
            /** @default 1.045 */
            growth: number;
            /** @default false */
            isBoss: boolean;
            key: string;
            name: string;
            /** @enum {string} */
            role: "attack" | "defense" | "hp" | "support";
            skills: string[];
            /** @default 0 */
            sortOrder: number;
        };
        FactionDef: {
            /** @default  */
            icon: string;
            key: string;
            /** @default  */
            lore: string;
            name: string;
            /** @default 0 */
            sortOrder: number;
        };
        GameConfigDef: {
            group: string;
            /** @default  */
            help: string;
            key: string;
            label: string;
            value: number | string | boolean | {
                [key: string]: unknown;
            } | unknown[];
        };
        GearSetDef: {
            bonus: {
                chance?: number;
                flat?: number;
                pct?: number;
                /** @enum {string} */
                stat?: "hp" | "atk" | "def" | "spd" | "critRate" | "critDmg" | "res" | "acc";
                turns?: number;
            };
            /** @enum {string} */
            bonusType: "stat" | "lifesteal" | "regen" | "provokeOnHit" | "stunOnHit" | "burnOnHit" | "counterOnHit" | "tmOnDamageTaken";
            key: string;
            /** @default  */
            lore: string;
            name: string;
            pieces: 2 | 4;
            /** @default 0 */
            sortOrder: number;
        };
        GearSlotDef: {
            /** @default false */
            accessory: boolean;
            allowedMainStats: ("hp" | "atk" | "def" | "spd" | "critRate" | "critDmg" | "res" | "acc")[];
            /** @default false */
            allowsPercentMain: boolean;
            /** @default 0 */
            ascensionRequired: number;
            /** @enum {string} */
            key: "weapon" | "helm" | "shield" | "gauntlets" | "cuirass" | "boots" | "ring" | "amulet" | "banner";
            name: string;
            /** @default 0 */
            sortOrder: number;
        };
        GearStatDef: {
            /** @default true */
            canBeMain: boolean;
            /** @default true */
            canBeSub: boolean;
            key: string;
            mainBase: number[];
            mainMax: number[];
            name: string;
            /** @default false */
            percent: boolean;
            /** @default 0 */
            sortOrder: number;
            /** @enum {string} */
            stat: "hp" | "atk" | "def" | "spd" | "critRate" | "critDmg" | "res" | "acc";
            subMax: number[];
            subMin: number[];
        };
        GetContentEntryResponse: {
            /** @enum {string} */
            contentType: "faction" | "status" | "skill" | "asset" | "champion" | "enemy" | "gearSet" | "gearSlot" | "gearStat" | "item" | "campaignChapter" | "stage" | "summonPool" | "shop" | "gameConfig";
            data: {
                [key: string]: unknown;
            };
            hasDraft: boolean;
            key: string;
            live: {
                [key: string]: unknown;
            } | null;
            pendingDelete: boolean;
        };
        ItemDef: {
            /** @enum {string} */
            category: "sigil" | "essence" | "tome" | "emblem" | "consumable" | "material";
            /** @default  */
            description: string;
            /** @default  */
            icon: string;
            key: string;
            name: string;
            /** @default {} */
            payload: {
                [key: string]: unknown;
            };
            /**
             * @default common
             * @enum {string}
             */
            rarity: "common" | "uncommon" | "rare" | "epic" | "legendary";
            /** @default 0 */
            sortOrder: number;
        };
        ListContentEntriesResponse: {
            /** @enum {string} */
            contentType: "faction" | "status" | "skill" | "asset" | "champion" | "enemy" | "gearSet" | "gearSlot" | "gearStat" | "item" | "campaignChapter" | "stage" | "summonPool" | "shop" | "gameConfig";
            items: components["schemas"]["ContentEntry"][];
        };
        ListContentRevisionsResponse: {
            current: number;
            revisions: components["schemas"]["ContentRevisionSummary"][];
        };
        ListContentTypesResponse: {
            draftCount: number;
            rev: number;
            types: components["schemas"]["ContentTypeCount"][];
        };
        LoginRequest: {
            accountName: string;
            password: string;
        };
        PublishContentRequest: {
            /** @default  */
            note: string;
        };
        PublishResult: {
            rev: number;
            summary: components["schemas"]["ContentTotals"];
            validation: components["schemas"]["ContentValidationResult"];
        };
        RevertContentRequest: {
            rev: number;
        };
        RevertContentResponse: {
            rev: number;
        };
        SaveContentEntryRequest: {
            data: {
                [key: string]: unknown;
            };
        };
        SaveContentEntryResponse: {
            /** @enum {string} */
            contentType: "faction" | "status" | "skill" | "asset" | "champion" | "enemy" | "gearSet" | "gearSlot" | "gearStat" | "item" | "campaignChapter" | "stage" | "summonPool" | "shop" | "gameConfig";
            key: string;
            saved: boolean;
        };
        ShopDef: {
            /** @default 4 */
            baseSlots: number;
            /** @default 150 */
            crystalSlotCost: number;
            /** @default 4 */
            crystalSlots: number;
            /** @default  */
            description: string;
            key: string;
            name: string;
            offers: {
                /**
                 * @default silver
                 * @enum {string}
                 */
                currency: "silver" | "crystals";
                /** @default 0 */
                dailyLimit: number;
                gear?: {
                    rankMax: number;
                    rankMin: number;
                    rarityWeights: {
                        [key: string]: number;
                    };
                    /** @default [] */
                    setKeys: string[];
                };
                key: string;
                /** @enum {string} */
                kind: "item" | "gear" | "champion" | "currency";
                /** @default 1 */
                minAccountLevel: number;
                name: string;
                price: number;
                /** @default 0 */
                pricePerRank: number;
                /** @default 1 */
                quantity: number;
                /** @default  */
                refKey: string;
                /** @default 10 */
                weight: number;
            }[];
            /** @default 50 */
            refreshCost: number;
            /** @default 60 */
            restockMinutes: number;
            /** @default 0 */
            sortOrder: number;
        };
        SkillDef: {
            /** @default {} */
            aiHints: {
                dontRepeatWhileActive?: string;
                onlyBelowHpPct?: number;
                openWith?: boolean;
                /** @enum {string} */
                prefer?: "lowestHp" | "highestAtk" | "highestTm" | "random" | "lowestHpAlly";
            };
            /**
             * @default {
             *       "track": "attack"
             *     }
             */
            animation: {
                projectile?: string;
                shake?: boolean;
                /**
                 * @default attack
                 * @enum {string}
                 */
                track: "attack" | "cast" | "idle";
                vfx?: string;
            };
            components: ({
                chance?: number;
                condition?: {
                    status: string;
                    /** @constant */
                    type: "targetHasStatus";
                } | {
                    status: string;
                    /** @constant */
                    type: "targetMissingStatus";
                } | {
                    pct: number;
                    /** @constant */
                    type: "selfHpBelow";
                } | {
                    pct: number;
                    /** @constant */
                    type: "targetHpBelow";
                } | {
                    atLeast: number;
                    /** @constant */
                    type: "alliesDead";
                };
                /** @enum {string} */
                element?: "ember" | "tide" | "verdant" | "mist";
                /** @default 1 */
                hits: number;
                ignoreDefPct?: number;
                mult: number;
                /** @enum {string} */
                scale: "atk" | "def" | "maxHp" | "spd";
                /** @constant */
                type: "damage";
            } | {
                chance?: number;
                condition?: {
                    status: string;
                    /** @constant */
                    type: "targetHasStatus";
                } | {
                    status: string;
                    /** @constant */
                    type: "targetMissingStatus";
                } | {
                    pct: number;
                    /** @constant */
                    type: "selfHpBelow";
                } | {
                    pct: number;
                    /** @constant */
                    type: "targetHpBelow";
                } | {
                    atLeast: number;
                    /** @constant */
                    type: "alliesDead";
                };
                status: string;
                /**
                 * @default hitTargets
                 * @enum {string}
                 */
                target: "hitTargets" | "self" | "allAllies" | "lowestHpAlly" | "randomAlly" | "allEnemies";
                turns: number;
                /** @constant */
                type: "applyStatus";
            } | {
                chance?: number;
                condition?: {
                    status: string;
                    /** @constant */
                    type: "targetHasStatus";
                } | {
                    status: string;
                    /** @constant */
                    type: "targetMissingStatus";
                } | {
                    pct: number;
                    /** @constant */
                    type: "selfHpBelow";
                } | {
                    pct: number;
                    /** @constant */
                    type: "targetHpBelow";
                } | {
                    atLeast: number;
                    /** @constant */
                    type: "alliesDead";
                };
                mult: number;
                /** @enum {string} */
                scale: "atk" | "def" | "maxHp" | "spd";
                /**
                 * @default self
                 * @enum {string}
                 */
                target: "hitTargets" | "self" | "allAllies" | "lowestHpAlly" | "randomAlly" | "allEnemies";
                /** @constant */
                type: "heal";
            } | {
                chance?: number;
                condition?: {
                    status: string;
                    /** @constant */
                    type: "targetHasStatus";
                } | {
                    status: string;
                    /** @constant */
                    type: "targetMissingStatus";
                } | {
                    pct: number;
                    /** @constant */
                    type: "selfHpBelow";
                } | {
                    pct: number;
                    /** @constant */
                    type: "targetHpBelow";
                } | {
                    atLeast: number;
                    /** @constant */
                    type: "alliesDead";
                };
                mult: number;
                /** @enum {string} */
                scale: "atk" | "def" | "maxHp" | "spd";
                /**
                 * @default self
                 * @enum {string}
                 */
                target: "hitTargets" | "self" | "allAllies" | "lowestHpAlly" | "randomAlly" | "allEnemies";
                turns: number;
                /** @constant */
                type: "shield";
            } | {
                chance?: number;
                condition?: {
                    status: string;
                    /** @constant */
                    type: "targetHasStatus";
                } | {
                    status: string;
                    /** @constant */
                    type: "targetMissingStatus";
                } | {
                    pct: number;
                    /** @constant */
                    type: "selfHpBelow";
                } | {
                    pct: number;
                    /** @constant */
                    type: "targetHpBelow";
                } | {
                    atLeast: number;
                    /** @constant */
                    type: "alliesDead";
                };
                deltaPct: number;
                /**
                 * @default hitTargets
                 * @enum {string}
                 */
                target: "hitTargets" | "self" | "allAllies" | "lowestHpAlly" | "randomAlly" | "allEnemies";
                /** @constant */
                type: "turnMeter";
            } | {
                chance?: number;
                condition?: {
                    status: string;
                    /** @constant */
                    type: "targetHasStatus";
                } | {
                    status: string;
                    /** @constant */
                    type: "targetMissingStatus";
                } | {
                    pct: number;
                    /** @constant */
                    type: "selfHpBelow";
                } | {
                    pct: number;
                    /** @constant */
                    type: "targetHpBelow";
                } | {
                    atLeast: number;
                    /** @constant */
                    type: "alliesDead";
                };
                count: number | "all";
                /**
                 * @default allAllies
                 * @enum {string}
                 */
                target: "hitTargets" | "self" | "allAllies" | "lowestHpAlly" | "randomAlly" | "allEnemies";
                /** @constant */
                type: "cleanse";
            } | {
                chance?: number;
                condition?: {
                    status: string;
                    /** @constant */
                    type: "targetHasStatus";
                } | {
                    status: string;
                    /** @constant */
                    type: "targetMissingStatus";
                } | {
                    pct: number;
                    /** @constant */
                    type: "selfHpBelow";
                } | {
                    pct: number;
                    /** @constant */
                    type: "targetHpBelow";
                } | {
                    atLeast: number;
                    /** @constant */
                    type: "alliesDead";
                };
                count: number | "all";
                /**
                 * @default hitTargets
                 * @enum {string}
                 */
                target: "hitTargets" | "self" | "allAllies" | "lowestHpAlly" | "randomAlly" | "allEnemies";
                /** @constant */
                type: "dispel";
            } | {
                chance?: number;
                condition?: {
                    status: string;
                    /** @constant */
                    type: "targetHasStatus";
                } | {
                    status: string;
                    /** @constant */
                    type: "targetMissingStatus";
                } | {
                    pct: number;
                    /** @constant */
                    type: "selfHpBelow";
                } | {
                    pct: number;
                    /** @constant */
                    type: "targetHpBelow";
                } | {
                    atLeast: number;
                    /** @constant */
                    type: "alliesDead";
                };
                /** @constant */
                type: "extraTurn";
            } | {
                chance?: number;
                condition?: {
                    status: string;
                    /** @constant */
                    type: "targetHasStatus";
                } | {
                    status: string;
                    /** @constant */
                    type: "targetMissingStatus";
                } | {
                    pct: number;
                    /** @constant */
                    type: "selfHpBelow";
                } | {
                    pct: number;
                    /** @constant */
                    type: "targetHpBelow";
                } | {
                    atLeast: number;
                    /** @constant */
                    type: "alliesDead";
                };
                delta: number;
                /**
                 * @default self
                 * @enum {string}
                 */
                target: "hitTargets" | "self" | "allAllies" | "lowestHpAlly" | "randomAlly" | "allEnemies";
                /** @constant */
                type: "cooldown";
            })[];
            /** @default 0 */
            cooldown: number;
            /** @default  */
            description: string;
            key: string;
            name: string;
            /** @enum {string} */
            slot: "a1" | "a2" | "a3" | "a4" | "passive";
            /** @default 0 */
            sortOrder: number;
            targeting: {
                count?: number;
                /** @enum {string} */
                mode: "single" | "all" | "random" | "lowestHp" | "self";
                /** @enum {string} */
                side: "enemy" | "ally" | "self";
            };
            /** @default [] */
            upgrades: ({
                /** @constant */
                effect: "damage";
                pct: number;
            } | {
                /** @constant */
                effect: "chance";
                pct: number;
            } | {
                /** @constant */
                effect: "cooldown";
                /** @constant */
                turns: 1;
            } | {
                /** @constant */
                effect: "heal";
                pct: number;
            } | {
                /** @constant */
                effect: "shield";
                pct: number;
            })[];
        };
        StageDef: {
            /**
             * @default normal
             * @enum {string}
             */
            difficulty: "normal" | "hard" | "brutal";
            energyCost: number;
            /** @default {} */
            firstClearRewards: {
                [key: string]: number;
            };
            key: string;
            /** @enum {string} */
            mode: "campaign" | "dungeon" | "springs" | "proving" | "tutorial";
            number: number;
            parentKey: string;
            rewards: {
                championXp: number;
                drops: {
                    /** @default 0 */
                    gearChance: number;
                    /** @default 2 */
                    gearRankMax: number;
                    /** @default 1 */
                    gearRankMin: number;
                    /** @default {} */
                    gearRarityWeights: {
                        [key: string]: number;
                    };
                    /** @default [] */
                    gearSlots: ("weapon" | "helm" | "shield" | "gauntlets" | "cuirass" | "boots" | "ring" | "amulet" | "banner")[];
                    /** @default [] */
                    items: {
                        chance: number;
                        itemKey: string;
                        /** @default 1 */
                        max: number;
                        /** @default 1 */
                        min: number;
                    }[];
                };
                dropTableKey?: string;
                playerXp: number;
                silverMax: number;
                silverMin: number;
            };
            /** @default 0 */
            sortOrder: number;
            starRules: {
                /** @default 12 */
                maxTurns: number;
                /** @default true */
                noDeaths: boolean;
            };
            /** @default {} */
            unlock: {
                playerLevel?: number;
                previousStageKey?: string;
            };
            waves: {
                enemyKey: string;
                level: number;
                slot: number;
                /** @default 1 */
                stars: number;
            }[][];
        };
        StatusDef: {
            /** @default  */
            description: string;
            /** @enum {string} */
            engineType: "statModifier" | "damageOverTime" | "healOverTime" | "shield" | "skipTurn" | "skipTurnBreakOnDamage" | "forceTargetA1" | "blockBuffs" | "blockDebuffs" | "counterattack" | "allyProtection" | "reflectDamage" | "lifesteal" | "healReduction" | "unkillable";
            family: string;
            /** @default  */
            icon: string;
            key: string;
            /** @enum {string} */
            kind: "buff" | "debuff";
            name: string;
            /**
             * @default {
             *       "tick": "none",
             *       "maxStacks": 1
             *     }
             */
            params: {
                flat?: number;
                /** @default 1 */
                maxStacks: number;
                pct?: number;
                ratio?: number;
                /** @enum {string} */
                stat?: "hp" | "atk" | "def" | "spd" | "critRate" | "critDmg" | "res" | "acc";
                /**
                 * @default none
                 * @enum {string}
                 */
                tick: "none" | "ownerTurnStart" | "ownerTurnEnd";
                tickPct?: number;
            };
            /** @default 1 */
            potency: number;
            /** @default 0 */
            sortOrder: number;
        };
        SummonPoolDef: {
            /** @default  */
            description: string;
            entries: {
                championKey: string;
                /** @default false */
                featured: boolean;
                /** @default 10 */
                weight: number;
            }[];
            key: string;
            name: string;
            /** @default {} */
            pity: {
                [key: string]: {
                    after: number;
                    /** @default 1 */
                    maxBonus: number;
                    step: number;
                };
            };
            rates: {
                [key: string]: number;
            };
            sigilKey: string;
            /** @default 0 */
            sortOrder: number;
            /** @enum {string} */
            tenPullFloor?: "common" | "uncommon" | "rare" | "epic" | "legendary";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    adminLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Success. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AdminLoginResponse"];
                        /** @constant */
                        ok: true;
                        rev: number;
                    };
                };
            };
            /** @description No session, or the credentials were wrong. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
            /** @description Rate limited. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
            /** @description Unexpected server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
        };
    };
    adminLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AdminLogoutResponse"];
                        /** @constant */
                        ok: true;
                        rev: number;
                    };
                };
            };
            /** @description No session, or the credentials were wrong. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
            /** @description The session is valid but the account lacks the admin rank. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
            /** @description Unexpected server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
        };
    };
    adminMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AdminMeResponse"];
                        /** @constant */
                        ok: true;
                        rev: number;
                    };
                };
            };
            /** @description No session, or the credentials were wrong. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
            /** @description The session is valid but the account lacks the admin rank. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
            /** @description Unexpected server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
        };
    };
    listContentTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ListContentTypesResponse"];
                        /** @constant */
                        ok: true;
                        rev: number;
                    };
                };
            };
            /** @description No session, or the credentials were wrong. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
            /** @description The session is valid but the account lacks the admin rank. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
            /** @description Unexpected server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
        };
    };
    listContentEntries: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Content type path segment. */
                type: "factions" | "statuses" | "skills" | "assets" | "champions" | "enemies" | "gear-sets" | "gear-slots" | "gear-stats" | "items" | "chapters" | "stages" | "summon-pools" | "shops" | "config";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ListContentEntriesResponse"];
                        /** @constant */
                        ok: true;
                        rev: number;
                    };
                };
            };
            /** @description No session, or the credentials were wrong. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
            /** @description The session is valid but the account lacks the admin rank. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
            /** @description No such content type, entity or revision. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
            /** @description Unexpected server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
        };
    };
    getContentEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Content key (lowercase snake_case). */
                key: string;
                /** @description Content type path segment. */
                type: "factions" | "statuses" | "skills" | "assets" | "champions" | "enemies" | "gear-sets" | "gear-slots" | "gear-stats" | "items" | "chapters" | "stages" | "summon-pools" | "shops" | "config";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["GetContentEntryResponse"];
                        /** @constant */
                        ok: true;
                        rev: number;
                    };
                };
            };
            /** @description No session, or the credentials were wrong. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
            /** @description The session is valid but the account lacks the admin rank. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
            /** @description No such content type, entity or revision. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
            /** @description Unexpected server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
        };
    };
    saveContentEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Content key (lowercase snake_case). */
                key: string;
                /** @description Content type path segment. */
                type: "factions" | "statuses" | "skills" | "assets" | "champions" | "enemies" | "gear-sets" | "gear-slots" | "gear-stats" | "items" | "chapters" | "stages" | "summon-pools" | "shops" | "config";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveContentEntryRequest"];
            };
        };
        responses: {
            /** @description Success. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["SaveContentEntryResponse"];
                        /** @constant */
                        ok: true;
                        rev: number;
                    };
                };
            };
            /** @description The request body failed validation. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
            /** @description No session, or the credentials were wrong. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
            /** @description The session is valid but the account lacks the admin rank. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
            /** @description No such content type, entity or revision. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
            /** @description Unexpected server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
        };
    };
    deleteContentEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Content key (lowercase snake_case). */
                key: string;
                /** @description Content type path segment. */
                type: "factions" | "statuses" | "skills" | "assets" | "champions" | "enemies" | "gear-sets" | "gear-slots" | "gear-stats" | "items" | "chapters" | "stages" | "summon-pools" | "shops" | "config";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["DeleteContentEntryResponse"];
                        /** @constant */
                        ok: true;
                        rev: number;
                    };
                };
            };
            /** @description No session, or the credentials were wrong. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
            /** @description The session is valid but the account lacks the admin rank. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
            /** @description No such content type, entity or revision. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
            /** @description Unexpected server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
        };
    };
    discardContentDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Content key (lowercase snake_case). */
                key: string;
                /** @description Content type path segment. */
                type: "factions" | "statuses" | "skills" | "assets" | "champions" | "enemies" | "gear-sets" | "gear-slots" | "gear-stats" | "items" | "chapters" | "stages" | "summon-pools" | "shops" | "config";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["DiscardContentDraftResponse"];
                        /** @constant */
                        ok: true;
                        rev: number;
                    };
                };
            };
            /** @description No session, or the credentials were wrong. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
            /** @description The session is valid but the account lacks the admin rank. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
            /** @description No such content type, entity or revision. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
            /** @description Unexpected server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
        };
    };
    diffContent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ContentDiff"];
                        /** @constant */
                        ok: true;
                        rev: number;
                    };
                };
            };
            /** @description No session, or the credentials were wrong. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
            /** @description The session is valid but the account lacks the admin rank. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
            /** @description Unexpected server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
        };
    };
    discardAllDrafts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["DiscardAllDraftsResponse"];
                        /** @constant */
                        ok: true;
                        rev: number;
                    };
                };
            };
            /** @description No session, or the credentials were wrong. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
            /** @description The session is valid but the account lacks the admin rank. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
            /** @description Unexpected server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
        };
    };
    publishContent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishContentRequest"];
            };
        };
        responses: {
            /** @description Success. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PublishResult"];
                        /** @constant */
                        ok: true;
                        rev: number;
                    };
                };
            };
            /** @description The request body failed validation. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
            /** @description No session, or the credentials were wrong. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
            /** @description The session is valid but the account lacks the admin rank. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
            /** @description Unexpected server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
        };
    };
    revertContent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevertContentRequest"];
            };
        };
        responses: {
            /** @description Success. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["RevertContentResponse"];
                        /** @constant */
                        ok: true;
                        rev: number;
                    };
                };
            };
            /** @description The request body failed validation. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
            /** @description No session, or the credentials were wrong. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
            /** @description The session is valid but the account lacks the admin rank. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
            /** @description No such content type, entity or revision. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
            /** @description Unexpected server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
        };
    };
    listContentRevisions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ListContentRevisionsResponse"];
                        /** @constant */
                        ok: true;
                        rev: number;
                    };
                };
            };
            /** @description No session, or the credentials were wrong. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
            /** @description The session is valid but the account lacks the admin rank. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
            /** @description Unexpected server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
        };
    };
    validateContent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ContentValidationResult"];
                        /** @constant */
                        ok: true;
                        rev: number;
                    };
                };
            };
            /** @description No session, or the credentials were wrong. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
            /** @description The session is valid but the account lacks the admin rank. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
            /** @description Unexpected server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
        };
    };
    adminOverview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AdminOverview"];
                        /** @constant */
                        ok: true;
                        rev: number;
                    };
                };
            };
            /** @description No session, or the credentials were wrong. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
            /** @description The session is valid but the account lacks the admin rank. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
            /** @description Unexpected server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
        };
    };
    getContentBundle: {
        parameters: {
            query?: never;
            header?: {
                /** @description ETag from a previous bundle response. */
                "If-None-Match"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ContentBundle"];
                        /** @constant */
                        ok: true;
                        rev: number;
                    };
                };
            };
            /** @description Content has not changed since the ETag you sent. */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unexpected server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: components["schemas"]["ApiError"];
                        /** @constant */
                        ok: false;
                        rev: number;
                    };
                };
            };
        };
    };
}
