#!/usr/bin/env node
/**
 * `pnpm sync-api` — regenerates `src/api/schema.d.ts` from the game repo's OpenAPI
 * artifact (ADMIN_ARCHITECTURE §3).
 *
 * The game server generates `docs/openapi/admin-api.json` from the Zod contracts in
 * `@mistvale/shared`, and this turns it into TypeScript. Both ends of the wire therefore
 * come from one definition: a server-side contract change shows up here as a type error
 * rather than as a runtime surprise.
 *
 * `--check` regenerates in memory and exits non-zero if the committed output differs, so
 * CI fails when someone forgets to run it.
 */

import { readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { pathToFileURL } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '..');
const source = resolve(repoRoot, '../MistvaleMobile/docs/openapi/admin-api.json');
const target = resolve(repoRoot, 'src/api/schema.d.ts');

const BANNER = `/**
 * Generated by \`pnpm sync-api\` from MistvaleMobile/docs/openapi/admin-api.json.
 *
 * Do not edit. Change the Zod contracts in the game repo's
 * \`packages/shared/src/openapi.ts\`, run \`pnpm openapi\` there, then \`pnpm sync-api\` here.
 */

`;

if (!existsSync(source)) {
  console.error(
    [
      'sync-api: the game repo artifact is missing.',
      '',
      `  Expected: ${source}`,
      '',
      '  The Admin Suite generates its API types from the game server\'s OpenAPI',
      '  document. Check out MistvaleMobile next to this repo and run `pnpm openapi`',
      '  there to produce it.',
    ].join('\n'),
  );
  process.exit(1);
}

const ast = await openapiTS(pathToFileURL(source), {
  alphabetize: true,
  emptyObjectsUnknown: true,
});
const generated = `${BANNER}${astToString(ast)}`;

if (process.argv.includes('--check')) {
  const existing = await readFile(target, 'utf8').catch(() => null);
  if (existing === null) {
    console.error(`sync-api: ${target} is missing. Run \`pnpm sync-api\`.`);
    process.exit(1);
  }
  if (existing !== generated) {
    console.error(
      'sync-api: src/api/schema.d.ts is out of date with the game repo contract.\n' +
        '  Run `pnpm sync-api` and commit the result.',
    );
    process.exit(1);
  }
  console.log('sync-api: generated types are up to date.');
} else {
  await writeFile(target, generated, 'utf8');
  console.log(`sync-api: wrote ${target}`);
}
